version: '3.4'

services:
  fase03.consumer:
    container_name: fase03-consumer
    image: ${DOCKER_REGISTRY-}fase03consumer
    ports:
      - 8082:8083
    build:
      context: .
      dockerfile: Fase04.Consumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
      - MessageSettings__Host=amqp://guest:guest@rabbitmq-fiap.brazilsouth.azurecontainer.io:5672/
    networks:
      - microservice-network

  SqlServerDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=123@Mudar
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - microservice-network

networks:
  microservice-network:
    external: true
