version: '3.4'

services:
  fase03.api:
    image: ${DOCKER_REGISTRY-}fase03api
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Fase04.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - MessageSettings__Host=amqp://guest:guest@rabbitmq-fiap.brazilsouth.azurecontainer.io:5672/
    depends_on:
      - rabbitmq
    networks:
      - microservice-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservice-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - microservice-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - microservice-network

  # SqlServerDB:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - SA_PASSWORD=123@Mudar
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - "1433:1433"
  #   networks:
  #     - microservice-network

networks:
  microservice-network:
    external: true